/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface EdmbnAccordion {
    'bordered': boolean;
    'expanded': boolean;
    'headerTitle': string;
    'lostFocusClose': boolean;
    'observeContent': boolean;
  }
}

declare global {


  interface HTMLEdmbnAccordionElement extends Components.EdmbnAccordion, HTMLStencilElement {}
  var HTMLEdmbnAccordionElement: {
    prototype: HTMLEdmbnAccordionElement;
    new (): HTMLEdmbnAccordionElement;
  };
  interface HTMLElementTagNameMap {
    'edmbn-accordion': HTMLEdmbnAccordionElement;
  }
}

declare namespace LocalJSX {
  interface EdmbnAccordion extends JSXBase.HTMLAttributes<HTMLEdmbnAccordionElement> {
    'bordered'?: boolean;
    'expanded'?: boolean;
    'headerTitle'?: string;
    'lostFocusClose'?: boolean;
    'observeContent'?: boolean;
  }

  interface IntrinsicElements {
    'edmbn-accordion': EdmbnAccordion;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


